### ISSUE TITLE
Remove hard-coded strings

### ISSUE THREAD

**Issue by Kalekdan** [mani-language/Mani#54]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*
There are various locations in the code where hard-coded strings are used which can make Máni fragile when moving to new systems and can incur unnecessary additional work when strings need to be updated.

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*
File locations should perhaps be replaced with environment variables. Other strings such as error messages could be stored in an external language file and then referenced with a key (e.g. getStringResource("errormsg.nullexception"); This would also make the Máni easy to port to foreign languages at some point.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by crazywolf132** [comment]
Can you please provide locations.

**Comment by Kalekdan** [comment]
The file locations actually seem to be updated since I last checked. It would only be a matter of updating the error messages then, which may not actually be required.
e.g. Inbuilt.java ln 193
`if ((arguments.get(0) instanceof Double) && (arguments.get(1) instanceof  Double)) {`
`        numPow = Math.pow((Double)arguments.get(0), (Double)arguments.get(1));`
`} else {`
`        return "pow : both arguments need to be a number!";`
`}`

**Comment by crazywolf132** [comment]
Yeah. Everything in that file should be migrated to their own modules. Except methods like `ask`

**Comment by crazywolf132** [comment]
I think this is still a problem. So we will keep this issue open

**Comment by crazywolf132** [comment]
Next task is to delete the `inbuilts` file
