### ISSUE TITLE
Switch statements.

### ISSUE THREAD

**Issue by crazywolf132** [mani-language/Mani#79]
**Is your feature request related to a problem? Please describe.**

> The addition of switch statements would make this language just that little bit better. It would remove the need for mass amounts of if statements.

**Describe the solution you'd like**

> Simply implementing another class (like maniFunction etc) to handle this.

**Describe alternatives you've considered**

> N/A

**Additional context**

> Some example code will be added here at a later stage.

**Comment by Kalekdan** [comment]
@crazywolf132 @ankitshubham97 I assume this can be closed now?

**Comment by ankitshubham97** [comment]
@Kalekdan Yes, this can be closed now.
