### ISSUE TITLE
Recode File API

### ISSUE THREAD

**Issue by crazywolf132** [mani-language/Mani#81]
**Name of the function or class, and location**
Please provide a link from GitHub to the exact location.

> https://github.com/crazywolf132/Mani/blob/master/src/com/mani/lang/Modules/files/files.java

**Reason for a re-code**
A clear and concise description of why this needs to be re-coded.

> This is currently a mess and the STDLib for it is a mess too, as there are functions that can be replaced... and functions we don't need. Maybe if we split it up a bit more, whilst combining some functions too.

**Will this affect anything else in the system?**
Please select one of the following:

> - [X] Yes
> - [ ] No

> It will also effect the Standard Library, this should maybe be altered along side this API

**Is the re-code required for any feature requests?**
If so, please specify the feature request it applies to.

> N/A

**Additional context**

**Comment by crazywolf132** [comment]
@Kalekdan If you would like something somewhat simple, this might be the task for you.

**Comment by Kalekdan** [comment]
Yeah, I'll take a look - will keep you updated how I get on

**Comment by crazywolf132** [comment]
Added in latest merge

**Comment by Kalekdan** [comment]
Reopening as there is still unused code I want to fix up and add to the files API. Either that or it should be removed to make it easier to maintain
