### ISSUE TITLE
Moving to org

### ISSUE THREAD

**Issue by crazywolf132** [mani-language/Mani#86]
It might be a good idea to move this repo over to an organisation. 

The reason for this is because I'm going to start building more projects around Máni. For example, `MARN`.

It will make it slightly easier to get access to. It will also make it easier to have the docs in a seperate repo.

It will also make it easier to add people as contributors. So they can help me run this project.

**Comment by crazywolf132** [comment]
@Kalekdan maybe you could accept the invite and move the examples repo to here.

**Comment by Kalekdan** [comment]
@crazywolf132 done

**Comment by crazywolf132** [comment]
This is finished now. We can close it.
