### ISSUE TITLE
Add Licencing.MD

### ISSUE THREAD

**Issue by Kalekdan** [mani-language/Mani#97]
**Is your feature request related to a problem? Please describe.**
Before first release, would probably be good to have some details on the licencing of Máni.

**Describe the solution you'd like**
Add a licencing.md file that details the licenses for the software

**Comment by crazywolf132** [comment]
I was thinking of looking for a licence we could use.

**Comment by crazywolf132** [comment]
@Kalekdan A license has been added.

https://github.com/mani-language/Mani/blob/master/LICENSE.md


We just need to add it to the top of each code file now.

**Comment by crazywolf132** [comment]
Done
